### ISSUE TITLE
No content at all

### ISSUE THREAD

**Issue by edouard-lopez** [diox/firefox-minimap-scroller#16]
After installing from the `dist/` directory I got the sidebar but it's empty and I got no log. I tested on:
- http://github.com ;
- http://duckduckgo.com ;
- http://google.com ;
- http://getbootstrap.com

I enabled chrome and addon debugging in the dev tools but still no log in the console.

**Comment by diox** [comment]
Yeah, it's broken, the extension is using old deprecated functions (and well, was built with an old deprecated SDK) that aren't working any more. 

I don't have the time nor the will to fix it right now, but I'll gladly take patches. To be honest the whole thing should be rewritten to work with e10s. Maybe it'd be simpler to try to use WebExtensions : https://wiki.mozilla.org/Browser_Extensions
