### ISSUE TITLE
Mouse event not released when exiting the sidebar

### ISSUE THREAD

**Issue by twidi** [diox/firefox-minimap-scroller#18]
If I mouse down on the scroller, move my mouse to scroll the page, and still with the button pressed, move the mouse cursor out of the sidebar, and then release the mouse button outside of the sidebar, now the scroller will move when hovering the sidebar.

**Comment by diox** [comment]
I'm not sure I can detect that the mouse is going outside the sidebar, but I should be able to fix the release mouse button part by checking if the button is currently being pressed in the `onmousemove` handler.
