### ISSUE TITLE
On Facebook the minimap is broken

### ISSUE THREAD

**Issue by MikkCZ** [diox/firefox-minimap-scroller#20]
On Facebook timeline, when scrolling down, the content from the upper parts of the page disappear (probably some "clever" Facebook unloading of the content). Do you think you could modify this behaviour so the content stays visible in the minimap?

**Comment by diox** [comment]
I don't have a facebook account so I can't test. Can you capture a video of the problem?

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the add-on development seems stopped anyway.
