### ISSUE TITLE
compatibility with Firefox ESR 52.5.3

### ISSUE THREAD

**Issue by grahamperrin** [diox/firefox-minimap-scroller#25]
With 52.5.3 (64-bit) on Mac OS X 10.9.5, the extension is enabled but non-functional; it's not a sidebar option.

**Comment by diox** [comment]
I'll change compatibility information to require 57 or higher, as it will also fix #23

**Comment by grahamperrin** [comment]
Hi, the same with this month's Firefox 52.8.1, 

![2018-06-15 23 07 46](https://user-images.githubusercontent.com/192271/41492384-bd0e56fa-70f6-11e8-906a-c245825ad766.png)

**Comment by diox** [comment]
Firefox < 57 will never be supported by this add-on. The compatibility info for the listing on AMO has been updated to reflect that.

**Comment by grahamperrin** [comment]
Thanks. I wasn't expecting compatibility :-) it was more, a gentle nudge re: AMO.  

https://addons.mozilla.org/addon/minimap-scroller-sidebar/ and https://addons.mozilla.org/addon/minimap-scroller-sidebar/versions/ look good now.
