### ISSUE TITLE
Add keybord shortcut to open minimap

### ISSUE THREAD

**Issue by MikkCZ** [diox/firefox-minimap-scroller#28]
The WebExtensions API should allow to define a shortcut to open the sidebar. That would be really useful to have, as the sidebar is used also for Bookmarks or History, which you can easily switch to with your keyboard (Ctrl+B and Ctrl+H), but cannot switch back to the minimap that easy.

**Comment by grahamperrin** [comment]
:100: 

I use vertical tabs (instead of, not in addition to, horizontal tabs) so the absence of a shortcut is a real drag. 

Back I go to Waterfox Classic where I can have the map _and_ vertical tabs :-)

**Comment by diox** [comment]
The WebExtensions API *does* have an API for keyboard shortcuts to open the sidebar and switch to the extension: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Special_shortcuts

I'll gladly accept a pull request implementing this.

**Comment by grahamperrin** [comment]
Thanks, I'd happily make a PR but I'm easily confused with code. Keeping it in mind …

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the add-on development seems stopped anyway.
