### ISSUE TITLE
Highlight results of 'find in page (CTRL+F)' in minimap

### ISSUE THREAD

**Issue by orgi** [diox/firefox-minimap-scroller#29]
This would be a really nice feature lot of people are missing in Firefix Quantum as the plugins which used to highlight the find results in the scroll bar no longer work there.
Hope this is possible using the minimap plugin - which btw. really looks nice.

**Comment by diox** [comment]
Hi,

This is a cool idea, but AFAIK this is not possible. I would need an event or the possibility to register some callback when the user initiates a search, and I don't think this exists.
